export const PERMISSIONS = {
  usersRead: 'users.read',
  usersReadPrivate: 'users.read_private',
  usersUpdateSelf: 'users.update_self',
  usersAvatarUpdateSelf: 'users.avatar_update_self',
  mediaReadDeleted: 'media.read_deleted',
  mediaReadUnmoderated: 'media.read_unmoderated',
  mediaReadExplicit: 'media.read_explicit',
  mediaUpload: 'media.upload',
  ratingsSet: 'ratings.set',
  ratingsRemove: 'ratings.remove',
  favoritesAdd: 'favorites.add',
  favoritesRemove: 'favorites.remove',
  commentsRead: 'comments.read',
  commentsReadDeletionReason: 'comments.read_deletion_reason',
  commentsCreate: 'comments.create',
  commentsDeleteOwn: 'comments.delete_own',
  commentsDeleteAny: 'comments.delete_any',
  moderationQueueRead: 'moderation.queue_read',
  moderationMediaApprove: 'moderation.media_approve',
  moderationMediaReject: 'moderation.media_reject',
  reportsCreate: 'reports.create',
  reportsAdminRead: 'reports.admin_read',
  reportsAdminUpdate: 'reports.admin_update',
  jobsRun: 'jobs.run',
  tagsManage: 'tags.manage',
  tagsAliasesManage: 'tags.aliases_manage',
} as const

export const STAFF_PERMISSIONS = [
  PERMISSIONS.usersReadPrivate,
  PERMISSIONS.mediaReadDeleted,
  PERMISSIONS.mediaReadUnmoderated,
  PERMISSIONS.moderationQueueRead,
  PERMISSIONS.moderationMediaApprove,
  PERMISSIONS.moderationMediaReject,
  PERMISSIONS.reportsAdminRead,
  PERMISSIONS.reportsAdminUpdate,
  PERMISSIONS.commentsDeleteAny,
  PERMISSIONS.jobsRun,
  PERMISSIONS.tagsManage,
  PERMISSIONS.tagsAliasesManage,
]
